version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  python:
    build: 
     context: ./fcModel
     dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
  node:
    build: 
     context: ./backend
     dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
  flutter:
    build:
      context: ./cra_frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  lb:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
volumes:
  pgdata:
